"""add publisher to games

Revision ID: 1c8a96bca549
Revises: f5538f81946f
Create Date: 2026-08-05 17:53:18.835255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8a96bca549'
down_revision: Union[str, Sequence[str], None] = 'f5538f81946f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('publisher', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'publisher')
    # ### end Alembic commands ###
