"""add latest_update_date to games

Revision ID: 3badeb3deda6
Revises: acb80a98d725
Create Date: 2026-05-23 17:30:11.557276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3badeb3deda6'
down_revision: Union[str, Sequence[str], None] = 'acb80a98d725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('latest_update_date', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'latest_update_date')
    # ### end Alembic commands ###
