"""add games and game matches tables

Revision ID: 88bae1286926
Revises: 0b44b9d79825
Create Date: 2026-03-19 16:37:56.141669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bae1286926'
down_revision: Union[str, Sequence[str], None] = '0b44b9d79825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('studio', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('release_date', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('game_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['tracker_id'], ['trackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_matches')
    op.drop_table('games')
    # ### end Alembic commands ###
